/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TeXCalc;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void loadResources() {
    	//InputStream in = getClass().getResourceAsStream("/mmacells.sty"); 
    	//BufferedReader reader = new BufferedReader(new InputStreamReader(in));
    	//assertTrue("good".equals(reader.lines()));
    }
}
